[package]
edition = "2018"
name = "router"
version = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = { version = "0.2" }
peg = { version = "0.8" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
harness = false
name = "benchmark"
