[package]
name = "wilbur-core"
version = "0.1.0"
edition = "2024"


[dependencies]
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
bytes.workspace = true
heather.workspace = true
